"""
Central configuration for the in-repo baseline training and evaluation.

NOTE: The deployed model uses Microsoft's Inception I3D (ml/i3d_msft/),
NOT the torchvision models configured here. This config is only used by
the in-repo baseline (ml/models/classifier.py, ml/training/train.py,
ml/evaluation/evaluate.py) for reproducible training experiments.

The deployed I3D model differs in key ways:
  - 64-frame clips (not 16)
  - [-1, 1] pixel normalization (not ImageNet mean/std)
  - 856-class label map (i3d_label_map_mvp-sft-full-v1.json)
"""

from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class DataConfig:
    """Dataset and preprocessing configuration."""

    # Paths (relative to ml/)
    processed_data_dir: Path = Path("../data/processed")

    # The number of classes is determined at runtime by label_map.json,
    # which is generated by the data pipeline (build_unified_dataset.py).
    # The value below is a reasonable default based on ASL Citizen's
    # vocabulary after filtering rare glosses.
    num_classes: int = 2000

    # Video clip properties (must match preprocess_clips.py settings)
    num_frames: int = 16        # frames uniformly sampled per clip
    frame_height: int = 224
    frame_width: int = 224

    # DataLoader
    num_workers: int = 4


@dataclass
class ModelConfig:
    """Model architecture configuration."""

    # Video backbone — pretrained on Kinetics-400
    backbone: str = "r3d_18"        # "r3d_18", "mc3_18", "r2plus1d_18"
    pretrained: bool = True
    backbone_freeze_epochs: int = 3  # freeze backbone for first N epochs

    # Classification head
    head_dropout: float = 0.5


@dataclass
class TrainConfig:
    """Training hyperparameters."""

    batch_size: int = 8             # smaller than image training due to video memory
    learning_rate: float = 1e-3
    weight_decay: float = 1e-4
    epochs: int = 30
    early_stopping_patience: int = 5

    # Scheduler
    scheduler: str = "cosine"
    warmup_epochs: int = 2

    # Checkpointing
    checkpoint_dir: Path = Path("checkpoints")
    save_every_n_epochs: int = 5

    # Device
    device: str = "mps"             # "cpu", "cuda", or "mps" (Apple Silicon)

    # Logging
    use_wandb: bool = False
    wandb_project: str = "eye-hear-u"


@dataclass
class Config:
    data: DataConfig = field(default_factory=DataConfig)
    model: ModelConfig = field(default_factory=ModelConfig)
    train: TrainConfig = field(default_factory=TrainConfig)
